version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

